### ISSUE TITLE
Open Hardware Monitor is not maintained anymore

### ISSUE THREAD

**Issue by davidkopp** [msg-systems/jpowermonitor#37]
[Open Hardware Monitor](https://github.com/openhardwaremonitor/openhardwaremonitor) is not maintained anymore. The last release was published on Dec 27, 2020. However, there are a few forks available, that can be used instead. The most promising fork seems to be [Libre Hardware Monitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor).
I haven't seen any breaking changes, so it can be used in the same way as Open Hardware Monitor with jPowerMonitor.

Therefore, I want to propose to replace Open Hardware Monitor with Libre Hardware Monitor in the documentation.

**Comment by deinerj** [comment]
Thanks a lot for the reference to [Libre Hardware Monitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor). 
We weren't aware about this and are glad to be able to recommend an open source tool again.
